### ISSUE TITLE
minimizer.rs parallelism

### ISSUE THREAD

**Issue by jianshu93** [ekimb/rust-mdbg#23]
Hello Rust-mdbg developer,

I see a few places where minimizer preparation could be further parallelized using rayon par_iter() and par_into_iter(). I understand it was parallelized via thread pooling, just wonder whether this will be a natural way to do in Rust.

Thanks,

Jianshu

**Comment by rchikhi** [comment]
Hi, thanks for the suggestion. I'm unsure if this would bring performance gains. If you feel otherwise, please feel free to provide a benchmark and I'd be happy to have a look.

**Comment by ekimb** [comment]
To add to this (it's been a while since this issue was opened), we already investigated ``rayon`` for parallelism, and the performance wasn't significantly improved (the parallelism is already achieved by parsing the input FASTA in parallel and obtaining minimizers serially in each thread).

If you end up testing it yourself and see an improvement, feel free to submit a pull request and we'll take a look! Thanks.
