### ISSUE TITLE
Nanopore metagenome assembly parameters

### ISSUE THREAD

**Issue by GeoMicroSoares** [ekimb/rust-mdbg#4]
Hi there,

Congratulations, this tool seems amazing and I can't wait to use it with my data!
Are there specific parameters that I can use/optimize with `rust-mdbg` to assemble Nanopore metagenomes?

Thanks.

**Comment by harish0201** [comment]
Curious as well! @GeoMicroSoares is your Nanopore dataset basecalled with either Bonito or Guppy with Bonito models? Would love to see the behaviour of the datasets ;)

**Comment by ekimb** [comment]
So far, `rust-mdbg` is intended to be used with HiFi reads due to the very low error rate, and Nanopore reads are currently out of scope based on our previous experimentation - feel free to run Nanopore reads and report back though, we would love to hear about the results. We do have a POA module that might be useful in assembling reads up to 4% error rate, but does not provide the same performance guarantees.

Regarding parameter optimization, we found that parameter performance is dependent on read length (similar to `k`-mer length in classical de Bruijn graphs). We provide an automatic selection of parameters (described in the documentation), but the optimization of the parameters for assembly quality is mostly an open question.

Hope that helps!

**Comment by rchikhi** [comment]
very much agreed with what Baris said, adding also: we only tested rust-mdbg on HiFi genomes, HiFi metagenomes, and small genomes having simulated reads with error rates approaching Nanopore levels, but never on Nanopore reads themselves. 

If you insist on trying rust-mdbg on Nanopore input, this is uncharted territory. As Baris said, use the `--error-correct` parameter, and there will be no guarantee that it will work; some parameter search will be necessary.. I'd recommend trying on 1 small Nanopore genome instead of directly a Nanopore metagenome.

**Comment by GeoMicroSoares** [comment]
Hi again all, thanks so much for the help.
I understand `rust-mdbg` wasn't directly created for this type of usage, but see a lot of potential in using rust-based software for this kind of data.
@harish0201 my dataset was created with `guppy 5.0`, using the recent superior accuracy (sup) model.
